yarnPath: .yarn/releases/yarn-3.5.0.cjs
npmScopes:
    projitect:
        npmRegistryServer: https://npm.pkg.github.com

npmRegistries:
    # Token expires on <DATE>
    //npm.pkg.github.com/:
        npmAuthToken: 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
